In [1]:
import torch

### Tensors

In [8]:
# uninitialized matrix
x = torch.empty(5, 3)
x

tensor(1.00000e-05 *
       [[ 0.0000, -0.0000,  0.0000],
        [-0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000],
        [ 0.0000, -0.0000,  9.1316]])

In [9]:
# randomly initialized matrix
x = torch.rand(5, 3)
x

tensor([[ 0.1640,  0.9445,  0.9316],
        [ 0.0045,  0.5753,  0.1237],
        [ 0.1826,  0.0400,  0.0505],
        [ 0.8539,  0.9693,  0.2950],
        [ 0.5593,  0.4414,  0.1603]])

In [10]:
# initialized with zeros and type long
x = torch.zeros(5, 3, dtype=torch.long)
x

tensor([[ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0]])

In [11]:
# initialized directly from data
x = torch.tensor([5.5, 3])
x

tensor([ 5.5000,  3.0000])

In [13]:
# initialized with another tensor
x = x.new_ones(5, 3, dtype=torch.float)
x = torch.randn_like(x, dtype=torch.float)
x

tensor([[ 0.5954,  0.4990, -0.4886],
        [ 0.8930,  0.3960,  0.1219],
        [ 0.2169, -0.6544,  1.1287],
        [-0.1906, -1.6054,  0.6213],
        [-0.4998,  0.4184,  2.4721]])

In [14]:
# get tensor size
x.size()

torch.Size([5, 3])

### Operations

In [16]:
y = torch.rand(5, 3)
y

tensor([[ 0.8165,  0.9968,  0.1109],
        [ 0.7888,  0.3627,  0.3930],
        [ 0.6493,  0.3456,  0.4608],
        [ 0.4703,  0.1782,  0.1711],
        [ 0.7467,  0.7535,  0.6922]])

In [18]:
# add 1
x + y

tensor([[ 1.4120,  1.4957, -0.3777],
        [ 1.6818,  0.7587,  0.5148],
        [ 0.8662, -0.3089,  1.5895],
        [ 0.2798, -1.4272,  0.7925],
        [ 0.2469,  1.1719,  3.1644]])

In [19]:
# add 2
torch.add(x, y)

tensor([[ 1.4120,  1.4957, -0.3777],
        [ 1.6818,  0.7587,  0.5148],
        [ 0.8662, -0.3089,  1.5895],
        [ 0.2798, -1.4272,  0.7925],
        [ 0.2469,  1.1719,  3.1644]])

In [23]:
# add in-place
y.add_(x)

tensor([[ 2.0074,  1.9947, -0.8664],
        [ 2.5748,  1.1546,  0.6367],
        [ 1.0830, -0.9633,  2.7182],
        [ 0.0892, -3.0325,  1.4138],
        [-0.2529,  1.5903,  5.6365]])

In [24]:
# indexing
y[:, 1]

tensor([ 1.9947,  1.1546, -0.9633, -3.0325,  1.5903])

In [26]:
# reshape
torch.reshape(y, (5, 3, 1))

tensor([[[ 2.0074],
         [ 1.9947],
         [-0.8664]],

        [[ 2.5748],
         [ 1.1546],
         [ 0.6367]],

        [[ 1.0830],
         [-0.9633],
         [ 2.7182]],

        [[ 0.0892],
         [-3.0325],
         [ 1.4138]],

        [[-0.2529],
         [ 1.5903],
         [ 5.6365]]])

In [29]:
# using view to reshape
x = torch.empty(4, 4)
x.view((4, 4, 1))

tensor([[[ 0.0000e+00],
         [-2.5244e-29],
         [ 0.0000e+00],
         [-2.5244e-29]],

        [[ 5.6052e-45],
         [ 0.0000e+00],
         [ 0.0000e+00],
         [ 0.0000e+00]],

        [[ 0.0000e+00],
         [ 0.0000e+00],
         [ 0.0000e+00],
         [ 0.0000e+00]],

        [[ 1.0774e-04],
         [ 1.5849e+29],
         [ 9.0371e-05],
         [ 3.7020e-40]]])

### NumPy Bridge

In [33]:
# comverting a torch tensor to a numpy array
x = torch.ones(5, 3)
x

tensor([[ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.]])

In [34]:
x_ = x.numpy()
x_

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]], dtype=float32)

In [35]:
# x and x_ share the same memory, changing one will change the other
x.add_(1)
x

tensor([[ 2.,  2.,  2.],
        [ 2.,  2.,  2.],
        [ 2.,  2.,  2.],
        [ 2.,  2.,  2.],
        [ 2.,  2.,  2.]])

In [36]:
x_

array([[ 2.,  2.,  2.],
       [ 2.,  2.,  2.],
       [ 2.,  2.,  2.],
       [ 2.,  2.,  2.],
       [ 2.,  2.,  2.]], dtype=float32)

In [37]:
# converting numpy array to torch tensor
x__ = torch.from_numpy(x_)
x__

tensor([[ 2.,  2.,  2.],
        [ 2.,  2.,  2.],
        [ 2.,  2.,  2.],
        [ 2.,  2.,  2.],
        [ 2.,  2.,  2.]])

### CUDA Tensors

In [38]:
torch.cuda.is_available()

False